
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'gg_vp_data'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'gg_vp_data'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

seeds:
  gg_vp_data:
    communes-france-2025:
      +alias: communes_france_2025
      +schema: staging

models:
  gg_vp_data:
    # Configuration globale : persistance de la documentation dans Snowflake
    +persist_docs:
      relation: true   # Descriptions tables/views dans COMMENT ON TABLE
      columns: true    # Descriptions colonnes dans COMMENT ON COLUMN

    staging:
      +materialized: view
      +schema: staging
      +persist_docs:
        relation: true
        columns: true

    intermediate:
      +materialized: view
      +schema: intermediate
      +persist_docs:
        relation: true
        columns: true

    marts:
      +materialized: table
      +schema: marts
      +persist_docs:
        relation: true
        columns: true

    observability:
      +materialized: view
      +schema: observability
      +persist_docs:
        relation: true
        columns: true
